### ISSUE TITLE
creating a tree with ancestor - decendent relation without knowledge of sample time

### ISSUE THREAD

**Issue by thebeancounter** [CompEvol/sampled-ancestors#3]
in the manual it's stated that the knowledge of the time of sample is required in order to create a tree with nodes being internal (ancestor) nodes, 

is that, at all possible to avoid that requirement and to infer father - son or ancestor relation between samples without any knowledge of their time of sample? 

thanks!

**Comment by gavryushkina** [comment]
In this implementation the ages are required. It is an interesting question though and I think if at least time order on the taxa is introduced then one can infer the ancestor-descendant relationship without the ages of the sampled nodes. This method might do what you want: 
 
https://arxiv.org/abs/1602.06893

Also, a good place to ask questions like this is the beast users forum:

https://groups.google.com/forum/#!forum/beast-users

where you will get a faster reply.

**Comment by thebeancounter** [comment]
thanks!
